// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQHTx11M0PiWMJFeJ3tbMz6R-6cPDvTg',
    appId: '1:539138703664:web:b48b2953fd5d8c1d8708f5',
    messagingSenderId: '539138703664',
    projectId: 'catatan-keuangan-online',
    authDomain: 'catatan-keuangan-online.firebaseapp.com',
    storageBucket: 'catatan-keuangan-online.appspot.com',
    measurementId: 'G-Q67JZYE5G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQzrY6d9nvKG_oLHTF6T6RUZb5g1Dnp8',
    appId: '1:539138703664:android:ab61055c8dda583a8708f5',
    messagingSenderId: '539138703664',
    projectId: 'catatan-keuangan-online',
    storageBucket: 'catatan-keuangan-online.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvG6L04loZCxn3g71s3yfpJ-DBXGqz40I',
    appId: '1:539138703664:ios:113fae7c7a8beb738708f5',
    messagingSenderId: '539138703664',
    projectId: 'catatan-keuangan-online',
    storageBucket: 'catatan-keuangan-online.appspot.com',
    iosClientId: '539138703664-g8b8if3ge2msit6asnjnecmnplke4o2b.apps.googleusercontent.com',
    iosBundleId: 'com.mahas.catatankeuanganonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvG6L04loZCxn3g71s3yfpJ-DBXGqz40I',
    appId: '1:539138703664:ios:113fae7c7a8beb738708f5',
    messagingSenderId: '539138703664',
    projectId: 'catatan-keuangan-online',
    storageBucket: 'catatan-keuangan-online.appspot.com',
    iosClientId: '539138703664-g8b8if3ge2msit6asnjnecmnplke4o2b.apps.googleusercontent.com',
    iosBundleId: 'com.mahas.catatankeuanganonline',
  );
}
