@startuml sample

hide circle
skinparam linetype ortho

entity "user" as user {
    *id : int <<auto>>
    --
    id_firebase : varchar(200)
    nama : varchar(100)
    email : varchar(100)
}

entity "perusahaan" as perusahaan {
    *id : int <<auto>>
    --
    id_user : int <<FK>>
}

entity "perusahaan_user" as perusahaan_user {
    *id : int <<auto>>
    --
    id_perusahaan : int <<FK>>
    id_user : int : NULL
    email : varchar(200) : NULL
    super_user : bool
}

entity "rekening" as rekening {
    *id : int <<auto>>
    --
    id_perusahaan : int <<FK>>
    nama : varchar(100)
    icon : varchar(100)
    saldo : decimal(19, 4)
}

entity "jenis_pengeluaran_pemasukan" as jenis_pengeluaran_pemasukan {
    *id : int <<auto>>
    --
    id_perusahaan : int <<FK>>
    nama : varchar(100)
    icon : varchar(100)
    pengeluaran : bool
}

entity "pengeluaran_pemasukan" as pengeluaran_pemasukan {
    *id : int <<auto>>
    --
    id_perusahaan : int <<FK>>
    id_user_create : int <<FK>>
    id_perusahaan_user : int <<FK>>
    id_jenis_pengeluaran_pemasukan : int <<FK>>
    id_rekening : int <<FK>>
    tanggal : datetime
    nilai : decimal(19, 4)
    catatan : varchar(500)
    pengeluaran : bool
}

entity "hutang_piutang" as hutang_piutang {
    *id : int <<auto>>
    --
    id_perusahaan : int <<FK>>
    id_user_create : int <<FK>>
    id_rekening : int <<FK>>
    tanggal : datetime
    tanggal_tempo : datetime
    nilai : decimal(19, 4)
    catatan : varchar(500)
    hitang : bool
}

entity "hutang_piutang_pembayaran" as hutang_piutang_pembayaran {
    *id : int <<auto>>
    --
    id_perusahaan : int <<FK>>
    id_hutang_piutang : int <<FK>>
    id_user_create : int <<FK>>
    id_rekening : int <<FK>>
    tanggal : datetime
    nilai : decimal(19, 4)
    catatan : varchar(500)
    hitang : bool
}

user ||--o| perusahaan
perusahaan_user }o--|| perusahaan
perusahaan_user |o--|| user
rekening }o--|| perusahaan
jenis_pengeluaran_pemasukan }o--|| perusahaan
jenis_pengeluaran_pemasukan }o--|| perusahaan
pengeluaran_pemasukan }o--|| perusahaan
pengeluaran_pemasukan }o--|| user
pengeluaran_pemasukan }o--|| user
pengeluaran_pemasukan }o--|| jenis_pengeluaran_pemasukan
pengeluaran_pemasukan }o--|| rekening
hutang_piutang }o--|| perusahaan
hutang_piutang }o--|| user
hutang_piutang }o--|| rekening
hutang_piutang_pembayaran }o--|| perusahaan
hutang_piutang_pembayaran }o--|| hutang_piutang
hutang_piutang_pembayaran }o--|| user
hutang_piutang_pembayaran }o--|| rekening

@enduml