name: catatan_keuangan_online
version: 1.0.0+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  firebase_remote_config: ^3.0.3
  firebase_analytics: ^10.0.3
  http: ^0.13.5
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  flutter_easyloading: ^3.0.5
  intl: ^0.17.0
  shimmer: ^2.0.0
  uuid: ^3.0.6
  modal_bottom_sheet: ^2.1.2
  fl_chart: ^0.55.2
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.7

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

